95 показывать кнопку оставить комментарий родителю под уроками со статусом ended и реализовать логику
moevm/MSE-2023-core-english-23 pull request #108
Opened 2023-04-17 13:45 UTC by ilya201232

2023-04-17 19:08 UTC, PashaThrowsException78 requested changes

2023-04-17 19:08 UTC, PashaThrowsException78 commented on src/main/java/core/english/mse2023/component/InlineKeyboardMaker.java
> +                            builder.button(TelegramInlineButtonsUtils.createInlineButton(
Эти кнопки лучше создавать заранее и давать им говорящие имена, потом внутри ифа уже пихать их в билдер. Потому что как оно щас -- неочевидно, что там за кнопки в разных ветках условия устанавливаешь

2023-04-17 19:08 UTC, PashaThrowsException78 commented on src/main/java/core/english/mse2023/dto/SetCommentForParentDTO.java
> +    private StateMachine<SetCommentForTeacherState, SetCommentForTeacherEvent> stateMachine;
Не Файнал ли она должна быть? Предположение прост

2023-04-18 16:14 UTC, dvur0g approved these changes

2023-04-19 07:27 UTC, merged