67 рефакторинг сервисного слоя
moevm/MSE-2023-core-english-23 pull request #134
Opened 2023-05-02 08:50 UTC by ilya201232

Провел большой рефакторинг сервисного слоя. Было сделано:
- Добавлены описания для каждого метода в сервисах (Javadoc)
- Методы в сервисах были переставлены местами так, чтобы сначала шли Get-методы, затем Create/Delete-методы, затем Set-методы и лишь затем вспомогательные методы
- Пересмотрена политика внедрения в сервисы других сервисов и репозиториев:
- - **Каждый сервис может включать в себя свой репозиторий и репозитории связанные с данным сервисом логически.** Например, LessonService включает в себя LessonRepository, как основной, и LessonHistoryRepository и LessonInfoRepository, как зависимые логически.
- - **Сервис может испортировать себе другой сервис, если реализация требуемой функциональности уже реализована в другом сервисе (т.е. чтобы не дублировать код).** Примером будет SubscriptionService, которому для создания уроков при создании подписки требуется код из LessonService
- - (Из за внедрения такой политики один DTO пришлось переделать, чтобы он хранил у себя не subscription UUID, а сам объект Subscription)
- Было изучено, что можно вызывать Transactional методы из других таких же методов без каких-либо проблем. Поэтому были внесены правки в код с учетом этой возможности
- В создаваемые объекты из базы данных были добавлены билдеры для более компактной записи создания таких объектов
- Метод getUserOrCreateNewOne() в UserService был разбит на два метода в связи с костыльностью его работы.
- Некоторые методы в сервисах возвращали boolean значение, указывающее на успешность выполнения задачи. Т.к. данный стиль выбивался из общего стиля всех других методов, код первых был перестроен. Теперь они выбрасывают исключения, которые можно отлавливать и обрабатывать

<br>

- В процессе тестирования выяснилось, что UI также требует рефакторинга вследствии остутствия некоторых кнопок для методов и банальной неудобностью работы с ним. Вероятно стоит в будущем разбить класс по созданию UI на большее количество методов.

2023-05-02 22:32 UTC, PashaThrowsException78 requested changes

2023-05-02 22:32 UTC, PashaThrowsException78 commented on src/main/java/core/english/mse2023/exception/LessonDoesNotExistsException.java
> +public class LessonDoesNotExistsException extends RuntimeException {
лучше убрать do

а вообще я бы именовал NoSuch.. как было, ну эт вкусовщина

2023-05-02 22:32 UTC, PashaThrowsException78 commented on src/main/java/core/english/mse2023/exception/SubscriptionDoesNotExistsException.java
> +public class SubscriptionDoesNotExistsException extends RuntimeException {
то же что и с уроком

2023-05-02 22:32 UTC, PashaThrowsException78 commented on src/main/java/core/english/mse2023/exception/UserDoesNotExistsException.java
> +public class UserDoesNotExistsException extends RuntimeException {
тож

2023-05-02 22:32 UTC, PashaThrowsException78 commented on src/main/java/core/english/mse2023/exception/SubscriptionAlreadyCanceledException.java
> +    public SubscriptionAlreadyCanceledException(String message) {
это очень узконаправленное исключение. сюда можно id передавать просто и подставлять его в сообщение уже в конструкторе

2023-05-02 22:32 UTC, PashaThrowsException78 commented on src/main/java/core/english/mse2023/exception/UserAlreadyExistsException.java
> +    public UserAlreadyExistsException(String message) {
сюда id сразу

вообще в подохных случаях хотя бы один из конструкторов оставляй такой

или если у тебя есть более общий эксепшн, который часто в конкретном кейсе используется -- обычно фабричный метод делают специально для такого кейса. ну это для общего развития больше

2023-05-02 22:32 UTC, PashaThrowsException78 commented on src/main/java/core/english/mse2023/exception/LessonDateOutsideSubscriptionException.java
> +    public LessonDateOutsideSubscriptionException(String message) {
конструктор без аргументов лучше

еще можешь добавить конструктор куда информацию о уроке и подписке передаешь чтобы даты печатались в логах

но вообще без аргументов достаточно будет

2023-05-02 22:32 UTC, PashaThrowsException78 commented on src/main/java/core/english/mse2023/service/impl/LessonServiceImpl.java
> +        createHistoryEvent(lesson, LessonHistoryEventType.CREATED);
эти методы не будут вызываться как транзакционные

2023-05-02 22:32 UTC, PashaThrowsException78 commented on src/main/java/core/english/mse2023/service/impl/LessonServiceImpl.java
> +        createHistoryEvent(lesson, LessonHistoryEventType.UPDATED);
короч когда дёргаешь методы этого же сервиса, они теряют транзакционность

чтобы метод стал транзакционным, спринг должен спроксировать его

у тебя же тут вызываются прям настоящие методы, без проксирования




с этим есть способы бороться но вообще можешь забить, мне былоб лень -- но вот просто чтобы ты понимал, это так работает

2023-05-02 22:32 UTC, PashaThrowsException78 commented on src/main/java/core/english/mse2023/service/LessonService.java
> +    Lesson finishLesson(UUID lessonId) throws LessonDoesNotExistsException, LessonAlreadyFinishedException;
лучше не выносить анчекед эксепшены в сигнатуры

2023-05-03 08:01 UTC, ilya201232 commented on src/main/java/core/english/mse2023/service/impl/LessonServiceImpl.java
> +        createHistoryEvent(lesson, LessonHistoryEventType.UPDATED);
Окей, спасибо. Я немного потыкался и решил, что это правда того не стоит. Там либо переделывать снова весь сервисный слой, либо делать self inject, что оказалось той еще задачкой. Короче, я оставлю все как есть

2023-05-08 12:31 UTC, ilya201232 commented
@PashaThrowsException78 апрувнул в телеге

2023-05-08 12:31 UTC, merged