14-fill-test-db
moevm/MSE-2023-core-english-23 pull request #49
Opened 2023-03-08 19:58 UTC by Lyubava0382

База данных заполнена тестовыми данными

2023-03-08 20:12 UTC, dvur0g requested changes

2023-03-08 20:12 UTC, dvur0g commented on src/main/java/core/english/mse2023/model/LessonHistory.java
> +@Entity(name = "lessonHistory")
лучше все названия таблиц оставить как есть, с маленькой буквы и с прочерками между словами. Обычно для БД такой стиль выбирают

2023-03-08 20:12 UTC, dvur0g commented on src/main/resources/db/changelog/changelog.yml
> +      id: 14-заполнить-бд-тестовыми-данными
тут лучше писать названия sql файла, который привязывается

2023-03-08 20:12 UTC, dvur0g commented on src/main/resources/db/changelog/changelog.yml
> +            path: classpath:db/changelog/sql/14-test-db.sql
а сам файл лучше нумеровать, отталкиваясь от предыдущего changelog файла, а также сам файл лучше назвать немного более понятно, например ```002-insert-test-data.sql```

2023-03-08 20:12 UTC, dvur0g commented on src/main/resources/db/changelog/sql/14-test-db.sql
> +INSERT INTO Users(id, name, lastname, telegram_id, email, password, role, created_when, modified_when)
тут лучше в telegram_id писать настоящие айдишки пользователей, чтобы мы могли с ними работать. Как их узнать, сейчас с тг напишу

2023-03-08 20:12 UTC, dvur0g commented on src/main/java/core/english/mse2023/model/LessonInfo.java
> +@Entity(name = "lessonInfo")
это название тоже лучше вернуть

2023-03-08 20:42 UTC, dvur0g approved these changes

2023-03-08 20:44 UTC, dvur0g requested changes

2023-03-08 20:44 UTC, dvur0g commented on src/main/resources/db/changelog/changelog.yml
> +      id: 002-insert-test-data.sql
тут приставка ```.sql``` не нужна, только название файла

2023-03-08 23:02 UTC, dvur0g requested changes

2023-03-08 23:02 UTC, dvur0g commented on src/main/resources/db/changelog/sql/002-insert-test-data.sql
> +VALUES ('f0e1a34a-bdd3-11ed-afa1-0242ac120002', 'Екатерина', 'Смирнова', '501727035', 'katy@gmail.com', 'katy',  'STUDENT', NOW() - 0.04, NOW() - 0.04);
у каждого юзера должен быть уникальный ```id```, (а тут у всех ```'f0e1a34a-bdd3-11ed-afa1-0242ac120002'```). БД не даёт записать значения из-за констреинта ```unique id```

2023-03-08 23:02 UTC, dvur0g commented on src/main/resources/db/changelog/sql/002-insert-test-data.sql
> +VALUES ('f0e1ad2c-bdd3-11ed-afa1-0242ac120002', 'Иван', 'Ахматов', '56830149', 'ivan@yandex.ru', 'PARENT', NOW() - 2, NOW() - interval - 0.005);
тут ```interval``` надо убрать

2023-03-08 23:02 UTC, dvur0g commented on src/main/resources/db/changelog/sql/002-insert-test-data.sql
> +VALUES ('c2826cb6-bdea-11ed-afa1-0242ac120002', UPDATED, NOW() - 0.9, '6b4e23aa-bddf-11ed-afa1-0242ac120002', NOW() - 1, NOW() - interval '23 hours');
тут ```interval``` надо убрать

2023-03-08 23:02 UTC, dvur0g commented on src/main/resources/db/changelog/sql/002-insert-test-data.sql
> +VALUES ('c2826f2c-bdea-11ed-afa1-0242ac120002', CREATED, NOW() - 1, '6b4e24b8-bddf-11ed-afa1-0242ac120002', NOW() - 1, NOW() - interval '1 day');
тут ```interval``` надо убрать

2023-03-09 08:18 UTC, ilya201232 approved these changes

2023-03-09 18:20 UTC, dvur0g approved these changes

2023-03-09 18:20 UTC, merged