40 реализовать логику создания подписки
moevm/MSE-2023-core-english-23 pull request #55
Opened 2023-03-11 20:57 UTC by ilya201232

2023-03-11 21:26 UTC, PashaThrowsException78 requested changes

2023-03-11 21:26 UTC, PashaThrowsException78 commented on src/main/java/core/english/mse2023/service/SubscriptionService.java
> +        } catch (ParseException e) {
вывести в консоль -- недостаточно.

во-первых, лучше прикрути логгирование, во-вторых -- если ты не можешь спарсить дату, у тебя не получится валидного объекта подписки. тут надо пробрасывать исключение (можешь создать кастомное)

2023-03-11 21:26 UTC, PashaThrowsException78 commented on src/main/java/core/english/mse2023/service/SubscriptionService.java
> +    public void create(SubscriptionCreationDTO creationDTO) {
оберни в транзакцию

2023-03-11 21:26 UTC, PashaThrowsException78 commented on src/main/java/core/english/mse2023/service/SubscriptionService.java
> +public class SubscriptionService {
лучше сделать интерфейс SubscriptionService и наследуй этот класс от него. к реализации припиши Impl в конец. с юзерсервисом также.

еще есть ломбоковская аннотация @Sl4j, это самый популярный способ логгировать. у тебя через sout всё выводится, сделай через логгеры.

2023-03-11 22:09 UTC, PashaThrowsException78 requested changes

2023-03-11 22:09 UTC, PashaThrowsException78 commented on src/main/java/core/english/mse2023/dto/InlineBtnDTO.java
> +            throw new IllegalArgumentException("Data string is bigger then expected! This isn't InlineButton data.");
а тут вообще IAE выбрасываешь. короче унифицируй это дело

2023-03-11 22:09 UTC, PashaThrowsException78 commented on src/main/java/core/english/mse2023/dto/InlineBtnDTO.java
> +            throw new RuntimeException("Data package is too big. " +
сделай кастомный экспепшн че-то типа ButtonCallbackDataLimitExceedException

2023-03-11 22:09 UTC, PashaThrowsException78 commented on src/main/java/core/english/mse2023/dto/InlineBtnDTO.java
> +            instance.command = dataSplit[0];
если правильно понял, у тебя тут нетривиальная логика маппинга строки на этот класс и обратно

раз уж это DTO, сделай какой-нибудь Encoder который этим заниматься будет, и убрать весь этот код из дто-класса.

и вообще это очень нехорошо, когда вызов toString может выбросить эксепшн.

2023-03-11 22:36 UTC, PashaThrowsException78 requested changes

2023-03-11 22:36 UTC, PashaThrowsException78 commented on src/main/java/core/english/mse2023/dto/SubscriptionCreationDTO.java
> +public class SubscriptionCreationDTO {
вот эту штуку через билдер собирать лучше. у ломбока аннотация есть

2023-03-11 22:36 UTC, PashaThrowsException78 commented on src/main/java/core/english/mse2023/hadler/ChangeRoleToAdminHandler.java
> +        throw new RuntimeException("The " + getClass() + " doesn't support update method.");
вот эти штуки мне вообще не нравятся. тогда уж сегрегируй интерфейсы, чтобы они поменьше были, а не все возможные методы в этом хэндлере.

и не выбрасывай RE, используй его более говорящих наследников, или создавай их сам

2023-03-11 22:36 UTC, PashaThrowsException78 commented on src/main/java/core/english/mse2023/hadler/ChangeRoleToParentHandler.java
> +        throw new RuntimeException("The " + getClass() + " doesn't support update method.");
то же самое. раздели интерфейс, так не должно быть

2023-03-11 22:36 UTC, PashaThrowsException78 commented on src/main/java/core/english/mse2023/hadler/CreateSubscriptionHandler.java
> +     * @throws IllegalArgumentException If user entered something that wasn't supposed to be in the form
больше для общего развития: джавадок не нужно писать приватным методам

2023-03-12 15:29 UTC, PashaThrowsException78 requested changes

2023-03-12 15:29 UTC, PashaThrowsException78 commented on src/main/java/core/english/mse2023/dto/inlineButton/InlineBtnDTO.java
> +public class InlineBtnDTO {
у тебя нет сеттеров и при этом есть NoArgConstructor. так и задумано?

2023-03-12 15:29 UTC, PashaThrowsException78 commented on src/main/java/core/english/mse2023/dto/inlineButton/InlineBtnDTOEncoder.java
> +    public String delimiter = " ";
публичная переменная

2023-03-12 15:29 UTC, PashaThrowsException78 commented on src/main/java/core/english/mse2023/hadler/ChangeRoleToAdminHandler.java
> +    private final UserServiceInterface service;
лучше нейми так:

интерфейс называешь по имени сервиса (UserService), имплементацию интерфейса UserServiceImpl

2023-03-12 15:29 UTC, PashaThrowsException78 commented on src/main/java/core/english/mse2023/state/IllegalStateException.java
> +public class IllegalStateException extends RuntimeException {
он же есть в jdk?

2023-03-12 16:56 UTC, dvur0g requested changes

2023-03-12 16:56 UTC, dvur0g commented on src/main/java/core/english/mse2023/cache/CacheData.java
> +            SendMessage message = new SendMessage();
можно подстановку chatId вынести в отдельный метод, т.к. он в следующем блоке catch тоже используется

2023-03-12 16:56 UTC, dvur0g commented on src/main/java/core/english/mse2023/dto/inlineButton/InlineBtnDTO.java
> +public class InlineBtnDTO {
Мелочь, но, думаю, для лучшего чтения кода, не стоит сокращать нигде слова и переименовать класс в InlineButtonDTO

2023-03-12 16:56 UTC, dvur0g commented on src/main/java/core/english/mse2023/dto/inlineButton/ButtonCallbackDataLimitExceedException.java
> +    public ButtonCallbackDataLimitExceedException(String msg) {
Мелочь, но, думаю, для лучшего чтения кода, не стоит сокращать нигде слова и переименовать аргумент в message

2023-03-12 16:56 UTC, dvur0g commented on src/main/java/core/english/mse2023/cache/IllegalUserInputException.java
> +    public IllegalUserInputException(String errorMsg) {
Мелочь, но, думаю, для лучшего чтения кода, не стоит сокращать нигде слова и переименовать аргумент в ```errorMessage```

2023-03-12 16:56 UTC, dvur0g commented on src/main/java/core/english/mse2023/dto/inlineButton/InlineBtnDTOEncoder.java
> +public class InlineBtnDTOEncoder {
Мелочь, но, думаю, для лучшего чтения кода, не стоит сокращать нигде слова и переименовать класс в InlineButtonDTOEncoder

2023-03-12 16:56 UTC, dvur0g commented on src/main/java/core/english/mse2023/dto/inlineButton/InlineBtnDTOEncoder.java
> +            throw new ButtonCallbackDataLimitExceedException("Data package is too big. " +
Сообщение об ошибке можно сохранить в переменной в самом классе ```ButtonCallbackDataLimitExceedException```, а в конструктор передавать только размер строки. Т.к. больше нигде это исключение не используется, да и вряд ли ему другое сообщение понадобится, оно описывает очень специфичный случай

2023-03-12 16:56 UTC, dvur0g commented on src/main/java/core/english/mse2023/dto/inlineButton/InlineBtnDTOEncoder.java
> +        String string = btnDTO.command + delimiter + btnDTO.stateIndex + delimiter + btnDTO.data;
переменную лучше назвать более информативно, например ```buttonData```, ```encodedButtonData``` или просто ```data```

2023-03-12 16:56 UTC, dvur0g commented on src/main/java/core/english/mse2023/dto/inlineButton/InlineBtnDTOEncoder.java
> +        // Checking if data is not exceeding the storage limit
комментарий можно убрать, и так понятно, что код делает. Кстати, проверку 
```
if (data.getBytes(StandardCharsets.UTF_8).length > 64) 
    return true; 
else 
    return false;
``` 
можно вынести в отдельный метод, т.к. тут она несколько раз встречается. И тогда по названию этого метода уже будет понятно, что за проверка происходит и комментарий к нему не понадобится

2023-03-12 16:56 UTC, dvur0g commented on src/main/java/core/english/mse2023/dto/inlineButton/InlineBtnDTOEncoder.java
> +        // Checking if data string contain the expected number of parameters
тоже в место комментария можно вынести проверку в отдельный метод с говорящим названием. Просто принято, что комментарии - это плохой тон, из кода и названий методов и так должно быть понятно, что код делает. Исключение - это описание классов, интерфейсов, методов интерфейсов и некоторый методов классов. За них отдельный лайк 👍

2023-03-12 16:56 UTC, dvur0g commented on src/main/java/core/english/mse2023/dto/inlineButton/InlineButtonCallbackDataParseException.java
> +    public InlineButtonCallbackDataParseException(String msg) {
также, думаю, можно аргумент назвать ```message```

2023-03-12 16:56 UTC, dvur0g commented on src/main/java/core/english/mse2023/hadler/CreateSubscriptionHandler.java
> +    private final Cache<String, SubscriptionCreationDTO> subscriptionCreationDTOCache = Caffeine.newBuilder()
думаю, в названии переменной ```DTO``` излишне, т.к. понятно, что мы в кеше только дтошки храним

2023-03-12 16:56 UTC, dvur0g commented on src/main/java/core/english/mse2023/hadler/CreateSubscriptionHandler.java
> +        // Sending start message
также тут думаю, если какому-то куску кода удобно присваевается комментарий, то лучше этот кусок вынести в отдельный метод

2023-03-12 16:56 UTC, dvur0g commented on src/main/java/core/english/mse2023/hadler/CreateSubscriptionHandler.java
> +                log.error("DTO instance wasn't created yet! Cannot continue. User id: " + update.getMessage().getFrom().getId() + "; Current state: " + state.getClass().getName());
во всех логах удобнее использовать следующую конструкцию:

```log.error("DTO instance wasn't created yet! Cannot continue. User id: {}; Current state: {}",  update.getMessage().getFrom().getId(), state.getClass().getName());```

то есть в тексте сообщения ставить фигурные скобки ```{}```, а потом через запятую параметры. Оно всё подставится как надо

2023-03-12 16:56 UTC, dvur0g commented on src/main/java/core/english/mse2023/hadler/interfaces/Handler.java
> +    default SendMessage createMessage(String chatId, String msg) {
```msg``` тоже можно в ```message``` переименовать

2023-03-12 16:56 UTC, dvur0g commented on src/main/java/core/english/mse2023/hadler/interfaces/Handler.java
> +     * Returns command name to handle
Думаю, лучше написать ```Returns handler's command```

2023-03-12 16:56 UTC, dvur0g commented on src/main/java/core/english/mse2023/tgbot/TelegramBotMainClass.java
> +public class TelegramBotMainClass extends TelegramLongPollingBot {
слово ```Class``` в названии класса излишне, думаю этот класс можно назвать ```TelegramBot```

2023-03-12 16:56 UTC, dvur0g commented on src/main/java/core/english/mse2023/tgbot/TelegramBotMainClass.java
> +            .expireAfter(new Expiry<String, CacheData>() {
Думаю, создание ```Expiry``` лучше вынести в отдельный метод. Либо вообще создание всего кеша в отдельный метод вынести. Довольно громоздко выглядит

2023-03-12 16:56 UTC, dvur0g commented on src/main/java/core/english/mse2023/dto/inlineButton/InlineBtnDTOEncoder.java
> +    public String delimiter = " ";
Можно вообще статичной константой сделать

2023-03-12 16:56 UTC, dvur0g commented on src/main/java/core/english/mse2023/hadler/CreateSubscriptionHandler.java
> +    public void cleanUp(String id) {
возможно стоит переименовать метод в ```removeFromCacheBy``` чтобы было понятней, что делает метод

2023-03-12 16:56 UTC, dvur0g commented on src/main/java/core/english/mse2023/service/SubscriptionService.java
> +        List<Lesson> lessons = new ArrayList<>();
думаю, создание Уроков для Подписки стоит вынести в отдельный метод и здесь его вызывать

2023-03-13 00:11 UTC, dvur0g requested changes

2023-03-13 00:11 UTC, dvur0g commented on src/main/java/core/english/mse2023/service/SubscriptionServiceImpl.java
> +package core.english.mse2023.service;
все импелементации сервисов лучше вынести в пекейдж ```core.english.mse2023.service.impl```

2023-03-13 00:11 UTC, dvur0g commented on src/main/java/core/english/mse2023/hadler/interfaces/Handler.java
> +package core.english.mse2023.hadler.interfaces;
этот интерфейс лучше вынести в пекейдж ```core.english.mse2023.handler```. Кстати, в пекейдже ```hadler``` опечатка, должно быть ```handler```. А все реализации хендлеров лучше вынести в пекейдж ```core.english.mse2023.handler.impl```

2023-03-13 00:11 UTC, dvur0g commented on src/main/java/core/english/mse2023/hadler/interfaces/InteractiveHandler.java
> +package core.english.mse2023.hadler.interfaces;
этот интерфейс лучше вынести в пекейдж ```core.english.mse2023.handler```

2023-03-13 00:11 UTC, dvur0g commented on src/main/java/core/english/mse2023/dto/inlineButton/ButtonCallbackDataLimitExceedException.java
> +package core.english.mse2023.dto.inlineButton;
все исключения лучше вынести в пекейдж ```core.english.mse2023.exception```

2023-03-13 00:11 UTC, dvur0g commented on src/main/java/core/english/mse2023/dto/inlineButton/InlineButtonDTOEncoder.java
> +package core.english.mse2023.dto.inlineButton;
энкодер лучше вынести в пекейдж ```core.english.mse2023.encoder```

2023-03-13 00:11 UTC, dvur0g commented on src/main/java/core/english/mse2023/cache/IllegalUserInputException.java
> +package core.english.mse2023.cache;
все исключения лучше вынести в пекейдж ```core.english.mse2023.exception```

2023-03-13 00:11 UTC, dvur0g commented on src/main/java/core/english/mse2023/dto/inlineButton/InlineButtonCallbackDataParseException.java
> +package core.english.mse2023.dto.inlineButton;
все исключения лучше вынести в пекейдж ```core.english.mse2023.exception```

2023-03-13 00:11 UTC, dvur0g commented on src/main/java/core/english/mse2023/service/UserServiceImpl.java
> +package core.english.mse2023.service;
все импелементации сервисов лучше вынести в пекейдж ```core.english.mse2023.service.impl```

2023-03-13 00:11 UTC, dvur0g commented on src/main/java/core/english/mse2023/state/subcriptionCreate/CreatedState.java
> +package core.english.mse2023.state.subcriptionCreate;
пекейдж лучше просто переименовать в ```core.english.mse2023.state.subcription```

2023-03-13 11:00 UTC, dvur0g approved these changes
🔥

2023-03-13 11:01 UTC, merged