Subscription cancel implemented
moevm/MSE-2023-core-english-23 pull request #75
Opened 2023-03-20 12:28 UTC by ilya201232

2023-03-20 14:07 UTC, PashaThrowsException78 requested changes

2023-03-20 14:07 UTC, PashaThrowsException78 commented on src/main/java/core/english/mse2023/service/impl/SubscriptionServiceImpl.java
> +        List<Lesson> lessons = lessonRepository.getAllBySubscriptionId(subscriptionId);
выглядит как метод лессонСервиса

2023-03-20 14:07 UTC, PashaThrowsException78 commented on src/main/java/core/english/mse2023/handler/impl/CreateSubscriptionHandler.java
> +            builder
тут лучше через forEach сделай

2023-03-20 14:07 UTC, PashaThrowsException78 commented on src/main/java/core/english/mse2023/handler/impl/GetAllSubscriptionsHandler.java
> +        InlineKeyboardBuilder builder = InlineKeyboardBuilder.instance();
можно чейнить. instance().button.row.button...

2023-03-20 14:07 UTC, PashaThrowsException78 commented on src/main/java/core/english/mse2023/handler/impl/MainMenuSubscriptionHandler.java
> +        InlineKeyboardBuilder builder = InlineKeyboardBuilder.instance();
тоже не обязательно. можешь InlineMarkupKeyboard keyboard = .instance().button().row().build();

2023-03-20 14:07 UTC, PashaThrowsException78 commented on src/main/java/core/english/mse2023/util/factory/TelegramInlineButtonsUtils.java
> +public class TelegramInlineButtonsUtils {
ну с таким название не надо в пакет factory класть

2023-03-20 14:07 UTC, PashaThrowsException78 commented on src/main/java/core/english/mse2023/util/factory/TelegramMessageUtils.java
> +public class TelegramMessageUtils {
сюда @UtilityClass ломбока

2023-03-20 14:07 UTC, PashaThrowsException78 commented on src/main/java/core/english/mse2023/handler/impl/ChangeRoleToAdminHandler.java
>          SendMessage message;
симпотичнее         SendMessage message = result ? 
                TelegramMessageUtils.createMessage(update.getMessage().getChatId().toString(), FAIL_TEXT)
                : TelegramMessageUtils.createMessage(
                        update.getMessage().getChatId().toString(), String.format(SUCCESS_TEXT, UserRole.ADMIN));

2023-03-20 14:07 UTC, PashaThrowsException78 commented on src/main/java/core/english/mse2023/handler/impl/GetMoreSubscriptionInfoHandler.java
> +        for (Lesson lesson : lessons) {
старайся такие вещи тоже в функциональном стиле делать

2023-03-20 14:07 UTC, PashaThrowsException78 commented on src/main/java/core/english/mse2023/service/SubscriptionService.java
> +    void cancelSubscription(UUID subscriptionId);
оно никакие эксепшены не выкинет> или бул возвращай или эксепшн кидай. надо быть уверенным что точно подписка отменилась. 

и сделай чек что текущий статус подписки не CANCELLED в имплементации тоже. если уже отменена надо как-то донести информацию об этом, булом или эксепшном

2023-03-20 14:09 UTC, PashaThrowsException78 commented on src/main/java/core/english/mse2023/handler/impl/ChangeRoleToAdminHandler.java
>          SendMessage message;
только форматирование норм сделай чтобы читабельно было

2023-03-20 16:16 UTC, PashaThrowsException78 requested changes

2023-03-20 16:16 UTC, PashaThrowsException78 commented on src/main/java/core/english/mse2023/service/impl/LessonServiceImpl.java
> +    @Override
транзакции забыл

2023-03-20 16:16 UTC, PashaThrowsException78 commented on src/main/java/core/english/mse2023/handler/impl/CancelSubscriptionHandler.java
> +            lessonService.cancelLessonsFromSubscription(subscriptionId);
отмена подписки должна быть атомарной. делай это в SubscriptionService::cancelSubscription

2023-03-20 16:16 UTC, PashaThrowsException78 commented on src/main/java/core/english/mse2023/service/impl/LessonServiceImpl.java
> +    public void createLessonsForSubscriptions(Subscription subscription, int amount) {
amount < 1 ниже вылетит ошибка в 55 строке

2023-03-21 20:47 UTC, dvur0g approved these changes
🔥

2023-03-22 00:21 UTC, PashaThrowsException78 approved these changes

2023-03-22 00:22 UTC, merged