Add Lesson Cancellation
moevm/MSE-2023-core-english-23 pull request #80
Opened 2023-03-25 21:17 UTC by Lyubava0382

2023-03-27 12:00 UTC, dvur0g requested changes

2023-03-27 12:00 UTC, dvur0g commented on src/main/java/core/english/mse2023/service/impl/LessonServiceImpl.java
> +            lessonInfo.setModifiedWhen(currentTime);
тут ещё не хватает `lessonInfoRepository.save(lessonInfo);`

2023-03-27 12:00 UTC, dvur0g commented on src/main/java/core/english/mse2023/service/impl/LessonServiceImpl.java
> +            lesson.setModifiedWhen(currentTime);
тут ещё не хватает `lessonRepository.save(lesson);`

2023-03-27 12:00 UTC, dvur0g commented on src/main/java/core/english/mse2023/handler/impl/CancelLessonHandler.java
> +                    .text(DONE_TEXT)
если нам вернулся статус `NOT_STARTED_YET`, разве мы в ответ шлём, что занятие отменилось? Занятие же отменено, если у него статус `CANCELLED_BY_TEACHER`

2023-03-27 12:05 UTC, dvur0g requested changes

2023-03-27 12:05 UTC, dvur0g commented on src/main/java/core/english/mse2023/service/impl/LessonServiceImpl.java
> +        return status;
тут надо возвращать статус уже сохранённого в БД урока. Т.е. `lesson.getStatus()`

2023-03-28 12:57 UTC, Lyubava0382 commented on src/main/java/core/english/mse2023/service/impl/LessonServiceImpl.java
> +            lesson.setModifiedWhen(currentTime);
Разве метод save нужно вызывать не только когда мы создаём новую запись? Мы ведь редактируем строчку таблицы, новую сущность не добавляя. И без save изменения сохраняются засчёт @Transactional

2023-04-03 07:00 UTC, ilya201232 commented on src/main/java/core/english/mse2023/service/impl/LessonServiceImpl.java
> +            lesson.setModifiedWhen(currentTime);
Кстати да, так и должно происходить)

2023-04-03 08:02 UTC, dvur0g approved these changes
🔥

2023-04-03 11:59 UTC, merged